version: '2.1'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "db", '-u', 'root', '-ppassword']
            timeout: 20s
            retries: 10
    
  reservation:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3001:3001'
